version: "3.3"

services:
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  gateway:
    environment:
      - PORT=5000
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    volumes:
      - ./gateway:/usr/src/app
  users:
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
    command: ["npm", "run", "dev"]
    volumes:
      - ./users:/usr/src/app
  subs:
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    command: air
    volumes:
      - ./subs:/go/src/app
    build:
      target: base
  posts:
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    command: air
    volumes:
      - ./posts:/go/src/app
    build:
      target: base
  comments:
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    command: air
    volumes:
      - ./comments:/go/src/app
    build:
      target: base
  vue:
    build: ./vue
    command: npm run serve
    volumes:
      - ./vue:/usr/src/app
