version: "3.3"

services:
  gateway: 
    build:
      target: prod
    ports: 
      - 80:5000
    environment: 
      - PORT=5000
    command: ["./gateway"]
  users:
    environment: 
    - PORT=5000
    - NODE_ENV=production