version: "3.3"

services:
  gateway:
    ports:
      - 80:5000
    environment:
      - PORT=5000
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    volumes:
      - ./gateway:/usr/src/app
  users:
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
    command: ["npm", "run", "dev"]
    volumes:
      - ./users:/usr/src/app
