version: "3.3"

services:
  gateway:
    ports:
      - 80:5000
    environment:
      - PORT=5000
      - NODE_ENV=production
    command: ["node", "./dist/server.js"]
  users:
    environment:
      - PORT=5000
      - NODE_ENV=production
    command: ["node", "./dist/server.js"]
